### ISSUE TITLE
Add code coverage badge to project.

### ISSUE THREAD

**Issue by BernardoSilva** [onesky/api-library-php5#18]
Add project to: https://scrutinizer-ci.com/

Once you added this project need to do those changes:

On `.travis.yml`  add this:
```yml
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
```

Create new file: `.scrutinizer.yml`
```yml
imports:
    - php

tools:
    external_code_coverage:
        timeout: 1200    # Timeout in seconds.
```

Add code coverage badge to `README.md`
```md
[![Code Coverage](https://scrutinizer-ci.com/g/onesky/api-library-php5/badges/coverage.png?b=master)](https://scrutinizer-ci.com/g/onesky/api-library-php5/?branch=master)
```
